# Generated by Django 5.1.3 on 2024-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
